### ISSUE TITLE
where to specify specific namespaces to monitor?

### ISSUE THREAD

**Issue by KlavsKlavsen** [gkarthiks/container-resource-exporter#1]
How do I specify the list of namespaces I want CRE to get stats from only?

**Comment by gkarthiks** [comment]
Hi @KlavsKlavsen, using the environment variable in the pod you can specify with the variable `WATCH_NAMESPACE`


```yaml
- env:
    - name: WATCH_NAMESPACE
        value: <namespace to watch>
```

**Comment by KlavsKlavsen** [comment]
But how do I add multple namespaces to watch, or do I have to deploy this in every namespace I want it to watch - and then point above to the namespace I just deployed it in?

**Comment by gkarthiks** [comment]
at present you can watch only in one namespace. Let me check if I can make it watchable across multiple namespaces

**Comment by KlavsKlavsen** [comment]
Then I could make a PR against your helm chart, to simply make it loop the role+rolebinding - so one is created for every  namespace - and bound to the SA in the namespace CRE runs in. (but I can't test until august when the Team here upgrades to latest openshift 3.11 - which gives me access to the namespaced metrics :)

**Comment by gkarthiks** [comment]
sure @KlavsKlavsen , feel free to do that.

**Comment by gkarthiks** [comment]
hi @KlavsKlavsen, the current code base is capable of accepting the multiple selected namespace for watching. There's not much of a change needed in the configuration.

Here's the details

To run the CRE in a contained namespace, i.e., watch only particular namespace; add the following environment variable WATCH_NAMESPACE. This can be easily accomplished with the downward api in Kubernetes as shown below.

```yaml
- env:
    - name: WATCH_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
```

The CRE can also take multiple namespace in a comma separated list. Like the below. Note that the namespaces should be added as the comma separated string and not individual strings by themselves.

```yaml
- env:
    - name: WATCH_NAMESPACE
      value: "default, kube-system, reporting"
```

Still, CRE will require a service account which has access to list all the pods under core v1 apiGroup and metrics apiGroup.
